### ISSUE TITLE
Some plugins not working 

### ISSUE THREAD

**Issue by vchernin** [flathub/com.github.wwmm.easyeffects#140]
Noticed the crystalizer and base loudness don't seem to have any effect on 6.2.5, could be a packaging error or an upstream bug but I didn't have time to investigate. (6.2.4 seems the same).

**Comment by wwmm** [comment]
I do not see any problem with them on my computer. These plugins haven't been touched in a while. What may be happening is that their effects is sometimes hard to notice. It depends on the kind of content they are being used.

**Comment by hsh9544** [comment]
affects me too

**Comment by vchernin** [comment]
Indeed I think crystalizer is hard to notice but working, and mda needed to be included as another plugin here. 

@hsh9544 Which plugin specifically were you having trouble with? Can you retest in ~5 hours after this comment?

**Comment by hsh9544** [comment]
I forgot to report, the problem solved after I updated the plugins (via
flatpak, I think) and it's now working as expected :)

Thanks for your kind response.
