### ISSUE TITLE
Error with libjack causes some plugins to not work

### ISSUE THREAD

**Issue by rigopoui** [flathub/com.github.wwmm.easyeffects#167]
### Problem description
I noticed that the 'Stereo Tools' plugin wasn't working for some reason. No input was being passed through it. Looking at my terminal, I got this output when loading the plugin.

```
(easyeffects:2): easyeffects-WARNING **: 09:50:27.787: 	lv2_wrapper.cpp:225	failed to instantiate http://calf.sourceforge.net/plugins/StereoTools
lilv_lib_open(): error: Failed to open library /app/lib/lv2/calf.lv2/calf.so (/usr/lib/x86_64-linux-gnu/libjack.so.0: undefined symbol: pw_thread_fill_attr)
```
It looks like this could be a problem problem with the flatpak, and not EasyEffects itself.
I have also opened an issue on the `easyeffects` repo - [link here](https://github.com/wwmm/easyeffects/issues/1968)

**Comment by vchernin** [comment]
this was fixed, see https://github.com/wwmm/easyeffects/issues/1968
