### ISSUE TITLE
Use calf plugins from flathub

### ISSUE THREAD

**Issue by Bleuzen** [flathub/com.github.wwmm.easyeffects#169]
Hi, currently EasyEffects bundles its own build of the calf plugins (in `easyeffects/util/flatpak/easyeffects-modules.json`).
However, here on flathub the calf plugins are already packaged as `org.freedesktop.LinuxAudio.Plugins.Calf`.
I have these plugins installed because I also use them in other hosts.
Now, everytime I launch EasyEffects, it prints a lot of these:

```
lilv_world_add_plugin(): warning: Duplicate plugin <http://calf.sourceforge.net/plugins/XOver2Band>
lilv_world_add_plugin(): warning: ... found in file:///app/lib/lv2/calf.lv2/
lilv_world_add_plugin(): warning: ... and      file:///app/extensions/Plugins/lv2/calf.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <http://calf.sourceforge.net/plugins/XOver3Band>
lilv_world_add_plugin(): warning: ... found in file:///app/lib/lv2/calf.lv2/
lilv_world_add_plugin(): warning: ... and      file:///app/extensions/Plugins/lv2/calf.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <http://calf.sourceforge.net/plugins/XOver4Band>
lilv_world_add_plugin(): warning: ... found in file:///app/lib/lv2/calf.lv2/
lilv_world_add_plugin(): warning: ... and      file:///app/extensions/Plugins/lv2/calf.lv2/ (ignored)
```

It would probably be a good idea to use the already packaged calf plugins instead of bundling them with EasyEffects.
Like it was already done for LSP, ZamPlugins and MDA.

**Comment by vchernin** [comment]
This sounds like a reasonable idea, I’ll try adjust it when I have a minute, but feel free to make a PR as it should only be a matter of editing the files in `util/flatpak` following the other plugins.

Do note one disadvantage is plugins must be bundled to work in gnome builder, but I think building less things is more useful.
