### ISSUE TITLE
New 7.0.8 release

### ISSUE THREAD

**Issue by Digitalone1** [flathub/com.github.wwmm.easyeffects#181]
It needs Linux Studio Plugins `1.2.10` as minimum version.

**Comment by vchernin** [comment]
Fixed in https://github.com/flathub/com.github.wwmm.easyeffects/pull/180

This had to be delayed due to the LSP `1.2.10` requirement, since we use a seperate package for LSP: https://github.com/flathub/org.freedesktop.LinuxAudio.Plugins.LSP/commit/cb3bebf4691b766b715ef41fd10a2e2b7ad7fae5
