### ISSUE TITLE
How to use the Deep Noise Remover effect with this flatpak

### ISSUE THREAD

**Issue by nmlynch94** [flathub/com.github.wwmm.easyeffects#191]
When adding the Deep Noise Remover effect to the input chain, it shows the following dialog:

![image](https://github.com/flathub/com.github.wwmm.easyeffects/assets/40608755/c9ab28e9-a655-493f-8148-74f5625c6098)

This seems to imply that the flatpak comes pre-installed with the dependencies for Deep Noise Remover, but it does not appear to be functioning. Not sure if I'm missing something or if this is an issue with the installation.

**Comment by wwmm** [comment]
Considering what is being shown in the window the Flatpak package probably does not have the library https://github.com/Rikorose/DeepFilterNet. How complicated it will be to add it I do not know.

**Comment by nmlynch94** [comment]
I'm doing some digging, and it looks like it does have it https://github.com/flathub/com.github.wwmm.easyeffects/blob/88fd8ac37a35c4315f9789fedc6abc7c5119ebf7/easyeffects-modules.json#L341. 

Trying to figure out why the application isn't seeing it. If I figure it out, I'll open a PR.

**Comment by nmlynch94** [comment]
Looks like the issue was a prior process that hadn't closed completely. I found the wiki showing how to generate debug logs. Once I killed the dupe process, the application launched as expected and detected the library.
