### ISSUE TITLE
Autostart .desktop file

### ISSUE THREAD

**Issue by pchmykh** [flathub/com.github.wwmm.easyeffects#194]
Hello!
Installed Easyeffects on Fedora workstation 40 here, Flatpak version.
Enabled autostart at preferences, app added file:
```
~$ cat ~/.config/autostart/com.github.wwmm.easyeffects.desktop 
[Desktop Entry]
Type=Application
Name=com.github.wwmm.easyeffects
Exec=flatpak run --command=easyeffects com.github.wwmm.easyeffects --gapplication-service
X-Flatpak=com.github.wwmm.easyeffects
```
It crashes every boot for me.
How to collect debug information?
Every time I am starting manually and closing the window, easyeffects just closes completely and processing is stopped.

Found https://github.com/flathub/com.github.wwmm.easyeffects/issues/3#issuecomment-908632842 this post and looks like it working properly.
Maybe it is a good idea to make file according this manual?
Thank you!

**Comment by vchernin** [comment]
https://github.com/flathub/com.github.wwmm.easyeffects/issues/3#issuecomment-908632842 is an old comment and should not be followed. The created autostart file using the auto start switch looks correct and works on my fedora 40 silverblue system.

> Every time I am starting manually and closing the window, easyeffects just closes completely and processing is stopped.

Do you have shutdown on window close enabled in easyeffects preferences?

**Comment by pchmykh** [comment]
Nope, shutdown on window close is disabled, but I have permanent crashes with created autostart file.

**Comment by vchernin** [comment]
To collect logs see https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs#basic-logs

If you can only reproduce the crash from what happens at start up, you way want to obtain the coredump from `flatpak-coredumpctl`.

**Comment by pchmykh** [comment]
Thank you for you time, I think this one can be closed. Crashes dissapeared when I am rebooted with autostart option enabled with default autostart .desktop file.
