### ISSUE TITLE
Set up CI in main repo

### ISSUE THREAD

**Issue by vchernin** [flathub/com.github.wwmm.easyeffects#30]
Arch is already setup. Ideally this could work without having to maintain the manifest within the repo as well.

**Comment by vchernin** [comment]
After thinking about this I think the most useful addition would be a nightly Flatpak repo pulling from master, I think that should be feasible enough for me to create.

I don't think adding another CI in addition to the Arch one would be very useful.

@wwmm what do you think about a nightly Flatpak repo? It would fulfill a similar use case as the AUR package.

Except with Flatpak they wouldn't need to compile anything, and there's no risk of making a mess of packages like if you added the Manjaro repo to Arch or something.

**Comment by wwmm** [comment]
>what do you think about a nightly Flatpak repo?

I think it would be useful. If you have the time to do that go ahead.

**Comment by vchernin** [comment]
there's now a beta (actually nightly) branch here, but potentially that could be simplified in the future to all be in the upstream repo. But that's for another day.
