### ISSUE TITLE
 Reset all settings doesn't work

### ISSUE THREAD

**Issue by vchernin** [flathub/com.github.wwmm.easyeffects#4]
- Also needs upstream testing, seems to partially work on Arch package.
- Probably related to https://github.com/wwmm/easyeffects/issues/894#issuecomment-775944406

**Comment by wwmm** [comment]
Which settings are not reset?

**Comment by wwmm** [comment]
>Probably related to Question: Assistance with Flatpak and 5.0.0 wwmm/easyeffects#894 (comment)

I see. Yes, the gsettings backend issue on flatpak is probably still a thing on EasyEffects. Ass far as I can see here on Arch Linux the reset seems to work. The are some controls in the window that do not really benefit from a reset. That function exists mostly to reset all plugins in one click.

**Comment by vchernin** [comment]
> I see. Yes. The gsettings backend issue on flatpak is probably still a thing on EasyEffects. Ass far as I can see here on Arch Linux the reset seems to work. The are some controls in the window that do not really benefit from a reset. That function exists mostly to reset all plugins in one click.

Yeah, I noticed it with the dark mode setting first.

**Comment by vchernin** [comment]
I investigated this a bit, the reset all settings is supposed to work in the libadwaita branch right (at least in non-Flatpak)?

I don't understand why `gsettings reset-recursively com.github.wwmm.easyeffects` from within the sandbox is unreliable. 

Most of the settings in the general page in the preferences window are reset, however:
1. The plugins don't seem to be reset at all. But the individual reset buttons on the plugin page do work though, how is that done?
2. The autostart switch isn't reset, but that's probably a seperate issue.
3. The spectrum page within the preferences window doesn't seem to change at all.

**Comment by vchernin** [comment]
```
$ gsettings reset-recursively
Usage:
  gsettings [--schemadir SCHEMADIR] reset-recursively SCHEMA[:PATH]

Reset all keys in SCHEMA to their defaults

Arguments:
  SCHEMADIR A directory to search for additional schemas
  SCHEMA    The name of the schema
  PATH      The path, for relocatable schemas
```

I guess maybe they're in different directories...

**Comment by vchernin** [comment]
I played with `gsettings` a bit and eventually made:
`gsettings list-relocatable-schemas | xargs -I {} gsettings reset-recursively {}:/app/share/glib-2.0/schemas/{}.gschema.xml/`

Strangely intermittently it will give a warning about broken pipe, but that's probably just because it gets overstressed or something.

Within the sandbox, this lists all schemas and resets them, even if they're relocatable. But it doesn't actually reset things in the app...

Meanwhile:
`gsettings list-schemas | xargs -n 1 gsettings reset-recursively`
Actually resets the spectrum page within preferences. Plugins are all deleted, and removed from view. But if you re-add them the settings are preserved...

**Comment by wwmm** [comment]
>is supposed to work in the libadwaita branch right (at least in non-Flatpak)?

It works in the libadwaita branch too.

**Comment by wwmm** [comment]
>The plugins don't seem to be reset at all. But the individual reset buttons on the plugin page do work though, how is that done?

I could have done in the plugins reset button the same thing I do in the reset all. But then Flatpak users would have none of the functions working. The problem with the approach taken in each plugin reset button is that we have to call the reset function for each configuration key independently https://github.com/wwmm/easyeffects/blob/366e78874709d459e62a298c9000b609a5946ac1/src/compressor_ui.cpp#L74. It is easy to forget a key in this method. Ideally I would like to just call `g_settings_reset(self->settings, "");` in all these reset buttons. The only thing forbidding me to do that is the lack of a compatible backend in Flatpak.

**Comment by wwmm** [comment]
>The spectrum page within the preferences window doesn't seem to change at all.

These keys are also reset outside of Flatpak. Or at least most of them.

>The autostart switch isn't reset, but that's probably a seperate issue.

It is something else indeed. This switch state is based on whether the autostart file exists. And the reset does not try to force it to be deleted.

**Comment by vchernin** [comment]
Wow, that is not ideal at all.

Maybe the gsettings reset functionality, or perhaps the keyfile backend is at fault here. Surely there is a better way when not using the dconf backend.

I'll try and find more info about how the gsettings schemas with keyfile are supposed to be reset, and why the `gsettings reset-recursively` does not do what it seems it should (even with dconf).

**Comment by wwmm** [comment]
As far as I remember the problem is not using the default backend. It does this task just fine. But for some reason it is not suitable to the Flatpak sandbox. What would be fine if the backend that is supposed to work in Flatpak had the recursive reset working.

**Comment by vchernin** [comment]
> As far as I remember the problem is not using the default backend. It does this task just fine. But for some reason it is not suitable for the Flatpak sandbox. What would be fine if the backend that is supposed to work in Flatpak had the recursive reset working.

I was [referring to this](https://github.com/wwmm/easyeffects/issues/894#issuecomment-776296604):

> The call to settings->reset("") does the recursive reset when the default backend is used. But for some reason gsettings reset-recursively com.github.wwmm.pulseeffects does not reset all the keys even when the default backend is used. So it won't solve the problem.

By default backend did you mean Dconf or keyfile? In Flatpak keyfile is default, but on host Dconf seems to be. It's clear keyfile doesn't work with recursive-reset somehow, but does Dconf? 

Another way of saying that, is the breaking change sandbox instead of host, or keyfile instead of Dconf backend? Or both?

**Comment by wwmm** [comment]
The keyfile backend is the problem. If I remember well it does not have the function for recursive reset implemented.

**Comment by vchernin** [comment]
I asked in #gtk, and they seemed to think it was undefined DConf behaviour, so I reported here: https://gitlab.gnome.org/GNOME/glib/-/issues/2554.

Hopefully they can clarify what the correct method/behaviour is.

**Comment by wwmm** [comment]
I am looking at the implementation of [gsettings_reset_recursively](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gsettings-tool.c#L436) and at least to me it doesn't seem recursive. But as I never write recursive code it is possible I am missing something obvious. Maybe @Digitalone1 understands how that function could be recursive. In any case I can try the same approach and see what happens.

**Comment by wwmm** [comment]
I have updated the libadwaita branch with a function based on [reset_all_keys](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gsettings-tool.c#L417) code. It works on Arch Linux. When I click on each plugin reset button its settings are reset.

Now I will try to see if that recursive approach works for our "reset all settings" button. I am skeptical about that. But who knows...

**Comment by wwmm** [comment]
`g_settings_list_children` returns null for our top level setting. What makes sense as we are not adding children to it. So that "recursive" approach in `gsettings_reset_recursively` is not going to work for us. Now I wonder what `g_settings_reset(self->settings, "");` is doing...

**Comment by vchernin** [comment]
I like how much cleaner https://github.com/wwmm/easyeffects/commit/70e3f1686be2cdc76a0bdf6c726f641bcae34078 is :)

With recursive, I think it’s just a naming thing. I usually think as recursion in programming to mean a function that calls itself. But here "recursive" seems more similar to what `-r` in `rm -r` does.

**Comment by wwmm** [comment]
>But here "recursive" seems more similar to what -r in rm -r does.

Not exactly. As far as I could understand even on a schema that actually has children that code would only reset the keys on the first level after the top. The ones below that won't be touched. It would have to actually be recursive to reset everything.  Whatever it is `g_settings_reset(self->settings, "")` is doing is something completely different.

**Comment by vchernin** [comment]
Ah, so it just resets the first level. I wonder why that was decided, that seems odd.

For the record, the new approach in the latest EasyEffects libadwaita branch commit works fine in Flatpak, so certainly at least https://github.com/wwmm/easyeffects/commit/70e3f1686be2cdc76a0bdf6c726f641bcae34078 was worthwhile.

**Comment by wwmm** [comment]
The current master branch is using a different approach that does not rely on undefined GSettings behavior. It should work on Flatpak now.

**Comment by vchernin** [comment]
It seems to work. When reseting all settings with plugins it removes all plugins and also resets their settings, is that intended?

There is a bit of a 3 second or so freeze while it resets, but it does work so thanks for fixing this one.

**Comment by wwmm** [comment]
>When reseting all settings with plugins added it removes all plugins and also resets their settings, is that intended?

Yes. That is what happens outside of Flatpak. So now it is equal.

>There is a bit of a 3 second or so freeze while it resets, but it does work so thanks for fixing this one.

That is because of the amount of settings being reset. Even the dconf backend that seems more optimized can have this freeze depending on how fast the cpu is. In my current cpu I did not notice this.  I am not sure if there is a way other than not trying to update too much settings at once.

**Comment by vchernin** [comment]
Is there not an easy way to reset the various files in parallel or something?

**Comment by wwmm** [comment]
>Is there not an easy way to reset the various files in parallel or something?

Not that I am away of. We can delay the actual writing of the values to its database. But eventually they will have to be written and it is up to GSettings how this is done. The most we can do is putting some interval between the calls for each key reset. But the choice of delay that is good on some computers may not be on others.

The real problem is the writing and not the reset action by itself. I had to do some optimizations to how we load presets because of this. I check if the new values is different before applying it. Otherwise the window may freeze. The problem is that when What we could try is checking somehow if the current key value is already equal to its default value before trying to reset.

**Comment by vchernin** [comment]
> What we could try is checking somehow if the current key value is already equal to its default value before trying to reset.

If writing is more intensive than reading, that does sound like it would help. In most cases users probably wouldn't have changed every setting (but if they did, reading every setting would make everything slower probably).

**Comment by vchernin** [comment]
I will close this since the issue is solved, maybe at some point I will investigate speeding it up though.
