### ISSUE TITLE
(beta branch) opening convolver crashes the application

### ISSUE THREAD

**Issue by vchernin** [flathub/com.github.wwmm.easyeffects#52]
For some reason opening the convolver plugin crashes the application on the beta branch, with commits from yesterday. The test build from gnome-builder seems to do the same.

```
filesystem error: directory iterator cannot open directory: No such file or directory [/var/home/v/.var/app/com.github.wwmm.easyeffects/config/easyeffects/irs]
```

Until I investigate this properly I will blame this on https://github.com/flathub/com.github.wwmm.easyeffects/commit/315869efd4dac85335ed07b21f7990f1d97c4e4c, but maybe it's an upstream error.

**Comment by wwmm** [comment]
That is bizarre. I do not have a crash on my computer but I have the subfolders on my computer since forever. Let me see what happens if I start EE without its config folder.

**Comment by wwmm** [comment]
It should work in the latest master. The code that was supposed to create the folder was being executed after one of the code paths that needed to access the folder :smile:

**Comment by vchernin** [comment]
I can confirm this is fixed on master now, nice :smile: 

How feasible is it to avoid these kind of crashes? Ideally a faulty plugin shouldn't be able to crash the entire application. Especially with the possibility of adding multiple instances of a plugin in the future.

**Comment by wwmm** [comment]
>How feasible is it to avoid these kind of crashes?

In that particular case checking for a exception in a try/catch block is probably enough.

**Comment by vchernin** [comment]
Ok good to know, I think this can be closed now then as the main issue is solved.
